import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "media_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "rooms_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "rooms_amenities_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "rooms_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "rooms_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_rooms_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_rooms_v_version_amenities_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_rooms_v_version_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_rooms_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "offers_conditions_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "offers_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_offers_v_version_conditions_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_offers_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "experiences_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "experiences_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "experiences_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_experiences_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_experiences_v_version_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_experiences_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "dining_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "dining_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_dining_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_dining_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "journal_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_journal_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "faqs_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "locations_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_gallery_block_images_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_gallery_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_rooms_showcase_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_experiences_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_dining_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_spa_highlight_block_features_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_spa_highlight_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonials_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats_block_stats_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_faq_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_location_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_journal_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_offers_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_feature_cards_block_cards_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_feature_cards_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_video_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "pages_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_gallery_block_images_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_gallery_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_rooms_showcase_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_experiences_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_dining_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_spa_highlight_block_features_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_spa_highlight_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonials_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats_block_stats_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_faq_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_location_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_journal_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_offers_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_feature_cards_block_cards_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_feature_cards_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_video_block_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_pages_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "site_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "header_nav_items_dropdown_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "header_nav_items_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "header_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "footer_columns_links_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "footer_columns_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "footer_legal_links_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "footer_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "booking_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "contact_info_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "seo_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "geo_settings_nested_places_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "geo_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  DROP TYPE "public"."_locales";
  CREATE TYPE "public"."_locales" AS ENUM('en', 'el');
  ALTER TABLE "media_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "rooms_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "rooms_amenities_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "rooms_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "rooms_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_rooms_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_rooms_v_version_amenities_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_rooms_v_version_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_rooms_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "offers_conditions_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "offers_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_offers_v_version_conditions_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_offers_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "experiences_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "experiences_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "experiences_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_experiences_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_experiences_v_version_highlights_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_experiences_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "dining_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "dining_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_dining_v_version_gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_dining_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "gallery_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "journal_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_journal_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "faqs_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "locations_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_content_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_content_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_gallery_block_images_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_gallery_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_rooms_showcase_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_experiences_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_dining_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_spa_highlight_block_features_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_spa_highlight_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_testimonials_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_stats_block_stats_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_stats_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_cta_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_faq_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_location_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_journal_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_offers_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_feature_cards_block_cards_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_feature_cards_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_blocks_video_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "pages_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_content_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_content_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_image_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_gallery_block_images_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_gallery_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_rooms_showcase_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_experiences_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_dining_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_spa_highlight_block_features_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_spa_highlight_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_testimonials_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_stats_block_stats_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_stats_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_cta_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_faq_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_location_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_journal_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_offers_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_feature_cards_block_cards_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_feature_cards_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_blocks_video_block_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_pages_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "site_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "header_nav_items_dropdown_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "header_nav_items_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "header_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "footer_columns_links_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "footer_columns_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "footer_legal_links_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "footer_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "booking_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "contact_info_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "seo_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "geo_settings_nested_places_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "geo_settings_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_rooms_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__rooms_v_published_locale";
  CREATE TYPE "public"."enum__rooms_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_rooms_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__rooms_v_published_locale" USING "published_locale"::"public"."enum__rooms_v_published_locale";
  ALTER TABLE "_offers_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__offers_v_published_locale";
  CREATE TYPE "public"."enum__offers_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_offers_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__offers_v_published_locale" USING "published_locale"::"public"."enum__offers_v_published_locale";
  ALTER TABLE "_experiences_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__experiences_v_published_locale";
  CREATE TYPE "public"."enum__experiences_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_experiences_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__experiences_v_published_locale" USING "published_locale"::"public"."enum__experiences_v_published_locale";
  ALTER TABLE "_dining_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__dining_v_published_locale";
  CREATE TYPE "public"."enum__dining_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_dining_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__dining_v_published_locale" USING "published_locale"::"public"."enum__dining_v_published_locale";
  ALTER TABLE "_journal_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__journal_v_published_locale";
  CREATE TYPE "public"."enum__journal_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_journal_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__journal_v_published_locale" USING "published_locale"::"public"."enum__journal_v_published_locale";
  ALTER TABLE "_pages_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_published_locale";
  CREATE TYPE "public"."enum__pages_v_published_locale" AS ENUM('en', 'el');
  ALTER TABLE "_pages_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__pages_v_published_locale" USING "published_locale"::"public"."enum__pages_v_published_locale";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."_locales" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__rooms_v_published_locale" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__offers_v_published_locale" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__experiences_v_published_locale" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__dining_v_published_locale" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__journal_v_published_locale" ADD VALUE 'fr';
  ALTER TYPE "public"."enum__pages_v_published_locale" ADD VALUE 'fr';`)
}
